"""Tests for GitHubCodeHost.open_pr_with_new_file and _put_file sha-omit behaviour."""
import base64
from unittest.mock import MagicMock

import pytest

from src.ci.github_app import GitHubCodeHost, GitHubError

REPO = "o/r"
PR_URL = "https://github.com/o/r/pull/42"


def _auth():
    a = MagicMock()
    a.installation_token.return_value = "ghs_tok"
    return a


class _Resp:
    def __init__(self, status, payload):
        self.status_code = status
        self._payload = payload

    def json(self):
        return self._payload


class _NewFileSess:
    """Mock session for open_pr_with_new_file tests.

    file_exists=False → GET /contents/ returns 404 (new file)
    file_exists=True  → GET /contents/ returns 200 with sha (existing file)
    existing_pr=URL   → GET /pulls returns that PR (idempotent path)
    """

    def __init__(self, *, file_exists: bool = False, existing_pr=None):
        self.file_exists = file_exists
        self.existing_pr = existing_pr
        # captured request bodies for assertions
        self.put_payload = None
        self.pr_payload = None

    def get(self, url, params=None, headers=None, timeout=None):
        if url.endswith("/pulls"):
            return _Resp(200, [{"html_url": self.existing_pr}] if self.existing_pr else [])
        if url.endswith(f"/repos/{REPO}"):
            return _Resp(200, {"default_branch": "main"})
        if "/git/ref/heads/" in url:
            return _Resp(200, {"object": {"sha": "base_sha_abc"}})
        if "/contents/" in url:
            if self.file_exists:
                encoded = base64.b64encode(b"old content").decode("utf-8")
                return _Resp(200, {"content": encoded, "sha": "existing_file_sha"})
            return _Resp(404, {"message": "Not Found"})
        return _Resp(404, {})

    def post(self, url, json=None, headers=None, timeout=None):
        if url.endswith("/git/refs"):
            return _Resp(201, {})
        if url.endswith("/pulls"):
            self.pr_payload = json
            return _Resp(201, {"html_url": PR_URL})
        return _Resp(404, {})

    def put(self, url, json=None, headers=None, timeout=None):
        self.put_payload = json
        return _Resp(200, {"commit": {"sha": "commit_sha_1"}})


# ---------------------------------------------------------------------------
# Tests for open_pr_with_new_file
# ---------------------------------------------------------------------------

class TestOpenPrWithNewFile:
    def _make_host(self, **sess_kwargs):
        sess = _NewFileSess(**sess_kwargs)
        host = GitHubCodeHost(
            auth=_auth(), installation_id="9",
            repo_full_name=REPO, session=sess,
        )
        return host, sess

    def test_new_file_creates_branch_and_pr(self):
        """GET /contents → 404 → no sha → creates file + draft PR."""
        host, sess = self._make_host(file_exists=False)
        url = host.open_pr_with_new_file(
            title="Add login spec",
            body="Generated by automation agent.",
            file_path="tests/login.spec.ts",
            content="test('login', () => {});",
            marker="mnemo:automation:abc123",
        )
        assert url == PR_URL
        # file was PUT (created)
        assert sess.put_payload is not None
        # sha key must be ABSENT for a new file (GitHub rejects sha=null)
        assert "sha" not in sess.put_payload
        # content matches
        decoded = base64.b64decode(sess.put_payload["content"]).decode("utf-8")
        assert decoded == "test('login', () => {});"
        # branch name derived from marker slug
        assert sess.pr_payload["head"] == "mnemo/automation/abc123"
        # PR is draft
        assert sess.pr_payload["draft"] is True
        # marker appended to PR body
        assert "<!-- mnemo:automation:abc123 -->" in sess.pr_payload["body"]

    def test_idempotent_returns_existing_pr_without_creating(self):
        """_find_pr_by_head returns existing PR → method returns it without PUT/POST."""
        host, sess = self._make_host(
            file_exists=False,
            existing_pr="https://github.com/o/r/pull/10",
        )
        url = host.open_pr_with_new_file(
            title="Add login spec",
            body="B",
            file_path="tests/login.spec.ts",
            content="...",
            marker="mnemo:automation:abc123",
        )
        assert url == "https://github.com/o/r/pull/10"
        # no file PUT and no PR created
        assert sess.put_payload is None
        assert sess.pr_payload is None

    def test_existing_file_updates_with_sha(self):
        """GET /contents → 200 with sha → PUT includes sha for an update."""
        host, sess = self._make_host(file_exists=True)
        url = host.open_pr_with_new_file(
            title="Update spec",
            body="Updated content.",
            file_path="tests/login.spec.ts",
            content="test('updated', () => {});",
            marker="mnemo:automation:upd1",
        )
        assert url == PR_URL
        assert sess.put_payload is not None
        # sha key must be PRESENT when updating an existing file
        assert sess.put_payload.get("sha") == "existing_file_sha"
        decoded = base64.b64decode(sess.put_payload["content"]).decode("utf-8")
        assert decoded == "test('updated', () => {});"

    def test_no_marker_uses_default_slug(self):
        """marker='' → branch = mnemo/automation/test."""
        host, sess = self._make_host(file_exists=False)
        host.open_pr_with_new_file(
            title="T", body="B",
            file_path="tests/a.spec.ts",
            content="content",
        )
        assert sess.pr_payload["head"] == "mnemo/automation/test"

    def test_api_error_on_default_branch_raises_github_error(self):
        """Propagates GitHubError when repo GET fails."""
        class _BoomSess(_NewFileSess):
            def get(self, url, params=None, headers=None, timeout=None):
                if url.endswith("/pulls"):
                    return _Resp(200, [])
                if url.endswith(f"/repos/{REPO}"):
                    return _Resp(500, {})
                return super().get(url, params=params, headers=headers, timeout=timeout)

        host = GitHubCodeHost(
            auth=_auth(), installation_id="9",
            repo_full_name=REPO, session=_BoomSess(),
        )
        with pytest.raises(GitHubError):
            host.open_pr_with_new_file(
                title="T", body="B",
                file_path="tests/a.spec.ts",
                content="c",
                marker="mnemo:automation:err1",
            )


# ---------------------------------------------------------------------------
# Tests for _put_file sha-omit behaviour
# ---------------------------------------------------------------------------

class TestPutFileShaOmit:
    """Unit tests for the _put_file sha-key logic."""

    def _make_host(self, captured):
        class _CaptureSess:
            def put(self, url, json=None, headers=None, timeout=None):
                captured["payload"] = json
                return _Resp(200, {"commit": {"sha": "x"}})

        return GitHubCodeHost(
            auth=_auth(), installation_id="9",
            repo_full_name=REPO, session=_CaptureSess(),
        )

    def test_omits_sha_when_file_sha_is_none(self):
        captured = {}
        host = self._make_host(captured)
        host._put_file("f.ts", "content", None, "branch", message="msg")
        assert "sha" not in captured["payload"]

    def test_omits_sha_when_file_sha_is_empty_string(self):
        captured = {}
        host = self._make_host(captured)
        host._put_file("f.ts", "content", "", "branch", message="msg")
        assert "sha" not in captured["payload"]

    def test_includes_sha_when_file_sha_is_set(self):
        captured = {}
        host = self._make_host(captured)
        host._put_file("f.ts", "content", "abc123", "branch", message="msg")
        assert captured["payload"]["sha"] == "abc123"
